# version: '3'

# services:
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     ports:
#       - "5000:5000"
#     environment:
#       MONGODB_HOST: database
#       MYSQL_USER: 27017
#       MYSQL_DATABASE: netflix
#     depends_on:
#       - database

#   database:
#     image: mongo:latest


version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map port 3000 of the host to port 3000 of the container
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map port 5000 of the host to port 5000 of the container
    depends_on:
      - database

  database:
    image: mongo:latest
