version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      MONGODB_HOST: database
      MYSQL_USER: 27017
      MYSQL_DATABASE: netflix
    depends_on:
      - database

  database:
    image: mongo:latest
