name: Build and Push Docker Images

on:
  push:
    branches: ['master'] # Trigger workflow on pushes to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/dockerfile
          push: true
          tags: soura700/frontend-image:latest

      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/dockerfile
          push: true
          tags: soura700/backend-image:latest

      # Add more steps as needed for additional services
